---
title: "Porn Star Scrape"
output: html_notebook
---

Goal: 
identify what makes a porn star get better ranking
what make her have better rating / view

```{r,message=FALSE}
set.seed(10000)
library(rvest)
library(XML)
library(RCurl)
library(dplyr)
library(stringr)
library(truncnorm)
library(readr)
library(lubridate)
library(scales)
knitr::opts_chunk$set(echo = FALSE)
# library(chron)
```


# get all the pages links
last page
```{r}
# need to go to page 2 to have the option of going to last page
lastpage = read_html('https://www.pornhub.com/pornstars?gender=female&page=2') %>%
  html_nodes('.page_smoothing') %>% html_text()
# last button number is the last page
lastpage = lastpage[length(lastpage)] 

pagenums = (1:lastpage %>% as.numeric()) %>% as.character()
# pagenum = paste0('&page=',pagenum) 
# pagelinks = paste0(base, pagenum)

# pagenums = (1:10) %>% as.character()
```


~ get all the link of stars

```{r}
getStarsLink = function( pagenum, base = 'https://www.pornhub.com/pornstars?gender=female&page=') {
  # get all the links on one page
  time1 = truncnorm::rtruncnorm(1, a = 5, b = 10, mean = 7)
  Sys.sleep(time1)
  base = paste0(base, pagenum)
  link = base %>% read_html()
  
  relative_link = link %>% html_nodes('.js-mxp') %>% html_attr('href')
  # dedup by only picking the odd idx
  idx = seq(1,length(relative_link)) %%2 >0  
  relative_link = relative_link[idx]
  relative_link %>% sapply(function(i) getRelativeURL(u = i, baseURL = base))
}

 star.links = pagenums[1:10] %>% sapply( function(num) getStarsLink(num))
 do.call(rbind, star.links %>% as.matrix)
df=  star.links%>% unlist %>% as.data.frame()

star.link = df %>% gather(key = 'a', value = 'link')
star.link %>% write.csv('porn_star_link1.csv', row.names = F)
# star.link %>% dim
```



~ parse through all the links to collect info

```{r}
# prevent character(0) to distort data
detectCharZero = function(i) {
  if (length(i) == 0) {
    i = NA
  } 
  i 
}

```


# parse star bio
```{r}

star1 = 'https://www.pornhub.com/pornstar/tachy-cardia' %>% read_html()
# blob about info

parseStar = function(star.link) {
  # time1 = truncnorm::rtruncnorm(1, a = 5, b = 10, mean = 7)
  # Sys.sleep(time1)
  # print(c(star.link, time1))
  m = rep(0,14)
  star1 = star.link %>% read_html()

    # ranking data
    
    rank_info = star1 %>% html_nodes(".big") %>% html_text()
    rank= star1 %>% html_nodes(".rankingInfo span") %>% html_text() %>% .[1]
    video_view = star1 %>% html_nodes(".infoBox.videoViews.tooltipTrig span") %>% html_text() 
    subscribe = star1 %>% html_nodes(".infoBox.subscribers span") %>% html_text() 
  
    # bio data
    name = star1 %>% html_nodes("h1") %>% html_text() %>%
      str_remove_all("[\\n]") %>%
      str_remove_all("[\\t]")
    
    info =  star1 %>% 
      html_nodes(".infoPiece") %>% html_text()
    info_text = info %>% paste(collapse = ',')
    gender = info[info %>% str_detect("Gender")]
    age = star1 %>% html_nodes('.infoPiece:nth-child(2) .smallInfo') %>% html_text()
    measurements = info[info %>% str_detect("Measurements")]
    height = info[info %>% str_detect("Height")]
    weight = info[info %>% str_detect('Weight')]
    profile_view =info[info %>% str_detect("Pornstar Profile Views")] 
    status =info[info %>% str_detect("Status")] 
    orientation = info[info %>% str_detect("Interested")] 
    verified = star1 %>% html_nodes('.verifiedIcon') %>% length
    
    # put all together
    m[1] = name %>% detectCharZero; m[2]= gender %>% detectCharZero; m[3] =age %>% detectCharZero; m[4]= measurements %>% detectCharZero; m[5] = height %>% detectCharZero; m[6] = profile_view %>% detectCharZero; m[7] = status %>% detectCharZero; m[8] = orientation %>% detectCharZero; m[9] = subscribe %>% detectCharZero; m[10] = video_view %>% detectCharZero; m[11] = rank %>% detectCharZero; m[12] = weight %>% detectCharZero(); m[13] = info_text %>% detectCharZero() ;  m[14] = verified %>% detectCharZero()

    return(m)
}
# parseStar(star.link1)
```

```{r}
link = 'https://www.pornhub.com/pornstar/lucy-cat'
parseVid = function(link) {
    print(link)
  star1 = link %>% read_html()
    m1 = cbind(
      star1 %>% html_nodes('.index-actors') %>% html_text() %>% str_trim(),
      star1 %>% html_nodes('.index-length') %>% html_text(),
          star1 %>% html_nodes('.index-views') %>% html_text(),
           star1 %>% html_nodes('.index-rating') %>% html_text(),
          star1 %>% html_nodes('.index-title') %>% html_text() %>% str_trim()
    ) 
    if (length(m1)==0) {
         m1 = data.frame(star = NA, Actors = NA, Length = NA, Views = NA, Rating=NA, Title = NA, Title_ct = NA)
      
    } else {
        colnames(m1) = m1[1,]
        m1 = m1[-1,] %>% as.data.frame(stringsAsFactors = F)
        if (nrow(m1) < 10) { # sanity check for edge cases
          m1 = data.frame(star = NA, Actors = NA, Length = NA, Views = NA, Rating=NA, Title = NA, Title_ct = NA)
        } else {
          t1 = strptime(m1$Length,"%M:%S")
          m1 = m1 %>% mutate(
             star = link %>% str_extract('pornstar/.+') %>% str_remove('pornstar/'),
             Actors = Actors %>% str_count("\\,") + 2,
             Length = t1$sec / 60 + t1$min,
             Rating = Rating %>%  str_remove_all("\\%") %>% as.numeric(),
             Title = `Video Name`,
             Title_ct = Title %>% nchar
            ) %>% dplyr::select(-`Video Name`)
        }
        
    }
  time1 = truncnorm::rtruncnorm(1, a = 3, b = 10, mean = 5)
  Sys.sleep(time1)

  return(m1 %>% as.matrix) 
}

# parseVid('https://www.pornhub.com/pornstar/riley-reid')
# parseVid(link)
```


```{r, cache = TRUE}
star.link = read_csv('porn_star_link1.csv')$link
# star.link %>% head
# idx = star.link %>% str_detect('lana-rhoades') %>% which
idx = 1
star.link.samp = star.link[c(idx:(idx+100))]

d = star.link %>% sapply(parseVid)

df.vid = do.call(rbind, d) %>% as.data.frame()
df.vid %>% write.csv('df_vid_new.csv', row.names = F)
df.vid %>% head
```




```{r}
# star.link.samp = star.link[c(501:1000)]
# 
# star.link %>% length
# 
# idx = 1
# for (i in 1:round(length(star.link)/500)) {
#   print(i)
#   star.link.samp = star.link[c(idx:(idx+500))]
#   idx = idx +500
#   # print(c(i,idx, paste0('star_bio', i, '.csv')))
#   b1 = star.link.samp %>% sapply(parseStar)
#   df1 = b1 %>% t() %>%  as.data.frame()
#   colnames(df1) = c('name', 'gender', 'age', 'measurements', 'height', 'profile_view', 'status', 'orientation', 'subscribe', 'video_view', 'rank', 'weight', 'info_text', 'verified')
#   write.csv(df1, paste0('star_bio', i, '.csv'), row.names = F)
# }
# 


star.link1 = star.link[idx]
parseStar(star.link1)
b1 = star.link %>% sapply(parseStar)
df1 = b1 %>% t() %>%  as.data.frame()

colnames(df1) = c('name', 'gender', 'age', 'measurements', 'height', 'profile_view', 'status', 'orientation', 'subscribe', 'video_view', 'rank', 'weight', 'info_text', 'verified')
# df1 %>% dim
# df1 %>% head
write.csv(df1, 'star_bio_new.csv', row.names = F)
```


```{r}
convertNum = function(str){
  # convert 32k to 32000
  if (str %>% str_detect('K')) {
    str = str %>% str_extract('([0-9]+\\,*\\.*)+') %>% str_remove_all(',') %>% as.numeric() *1000
  } else if (str %>% str_detect('M')){
    str = str %>% str_extract('([0-9]+\\,*\\.*)+') %>% str_remove_all(',') %>% as.numeric() *1000000
  } else {
    str = str %>% str_extract('([0-9]+\\,*\\.*)+') %>% str_remove_all(',') %>% as.numeric()
  }
  str
}
# convertNum('580,620,017')
library(eeptools)
ageFunc = function(age){
  
  if (is.na(age)) {
    return(NA)
  }
  if (str_detect(age, '^[0-9]{4}')) {
    age = age %>% ymd
  } else if (str_detect(age, '[0-9]{4}$')) {
    age = age %>% mdy
  } else {return(NA)}
  age_year = age_calc(age,units = 'years') 
  
  if (age_year >70) {
    age_year = NA
  }
  age_year
}
# ageFunc('1993-02-10')
# df1[2,]$video_view %>% convertNum
# df1 %>% write.csv('porn_out10.csv', row.names = F)

```


```{r}
df1 = read_csv('star_bio_new.csv')

df.star = df1 %>% mutate(
              
  gender = ifelse(gender %>% str_detect('Male'), 'M', 'F'),
               gender = ifelse(is.na(gender), 'F', gender),
               # dimension vars
               d1 = measurements %>% str_extract('[1-9]+[A-Z]'),
               cup = d1 %>% str_extract('[A-Z]') %>% factor(levels = c('A', "B", "C",'D', 'E')),
               d1 = d1 %>% str_remove_all('[A-Z]') %>% as.numeric(),
               d2 = measurements %>% str_extract('-[1-9].-') %>% str_remove_all('-') %>% as.numeric(),
               d3 = measurements %>% str_extract('[1-9].$') %>% str_remove_all('-') %>% as.numeric(),
               status = status %>% str_detect('Active'),
              # subscribe =  subscribe %>% convertNum,
              # # video_view1 = video_view %>%  convertNum, # buggy, to be fixed
              height = height %>% str_extract('[0-9]+ cm') %>% str_remove(' cm') %>% as.numeric(),
              weight = weight %>% str_extract('[0-9]+ lbs') %>% str_remove(' lbs')%>% as.numeric()
               # age1 = age %>% ageFunc() # buggy
               ) %>%
  dplyr::select(name,gender, d1, d2,d3, cup, height, weight, status)
# those 2 things cant compute using mutate
df.star$video_view1 = sapply(df1$video_view, convertNum)
df.star$age = sapply(df1$age, ageFunc)
df.star$star = df.star$name %>%str_replace_all(' ', '-') %>% tolower
# df.star$age %>% plot
df.star %>% head
```


```{r}
library(GGally)
ggpairs(df.bio1, columns = c('d1', 'd2', 'd3', 'cup', 'height', 'weight', 'video_view1', 'subscribe','score'))
```


```{r}
df.star$star = df.star$name %>%str_replace_all(' ', '-') %>% tolower
df.join = df.vid %>% full_join(df.star)
df.join %>% write.csv('df_join.csv', row.names = F)


df.join %>% head
df.join %>% dim

fit1 = lm(log(video_view1) ~d1 + d2 + d3 + cup + height + weight, data = df.join)

summary(fit1) 
```






























